
import React, { useState } from 'react';

export const IncomeCalculator: React.FC = () => {
  const [views, setViews] = useState<number>(100000000); // Default to 100M

  const minRPM = 0.00005; // $5000 / 100,000,000
  const maxRPM = 0.0005;  // $50000 / 100,000,000

  const minEarnings = views * minRPM;
  const maxEarnings = views * maxRPM;

  const formatViews = (val: number) => {
    if (val >= 1000000000) return (val / 1000000000).toFixed(1) + 'B';
    if (val >= 1000000) return (val / 1000000).toFixed(0) + 'M';
    return val.toLocaleString();
  };

  const formatCurrency = (val: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0,
    }).format(val);
  };

  return (
    <section className="py-16">
      <div className="bg-grid border border-zinc-800 rounded-[40px] p-8 md:p-12 overflow-hidden relative">
        <div className="absolute top-0 right-0 p-8 opacity-10 pointer-events-none">
          <div className="text-8xl font-black italic select-none">$</div>
        </div>

        <div className="max-w-2xl mx-auto space-y-12 relative z-10 text-center">
          <div className="space-y-4">
            <div className="inline-flex items-center gap-2 bg-zinc-900 border border-zinc-800 px-4 py-2 rounded-full text-zinc-500 text-[10px] font-black uppercase tracking-widest">
              <span className="text-[#b0ff3e] animate-pulse">●</span> The Profit Calculator
            </div>
            <h2 className="text-4xl md:text-5xl font-black tracking-tighter italic">
              Calculate Your <span className="text-[#b0ff3e]">Earnings</span>
            </h2>
            <p className="text-zinc-400 font-medium max-w-lg mx-auto leading-relaxed">
              Estimate your monthly revenue potential based on views generated by your AI Influencer accounts.
            </p>
          </div>

          <div className="bg-zinc-950/50 backdrop-blur-xl border border-zinc-800 p-8 rounded-3xl space-y-8">
            <div className="space-y-6">
              <div className="flex justify-between items-end">
                <label className="text-zinc-500 font-black uppercase text-[10px] tracking-[0.2em]">Estimated Monthly Views</label>
                <span className="text-3xl font-black text-white italic tracking-tighter">
                  {formatViews(views)}
                </span>
              </div>
              
              <input 
                type="range" 
                min="1000000" 
                max="1000000000" 
                step="1000000" 
                value={views} 
                onChange={(e) => setViews(parseInt(e.target.value))}
                className="w-full h-2 bg-zinc-800 rounded-lg appearance-none cursor-pointer accent-[#b0ff3e]"
              />
              
              <div className="flex justify-between text-[10px] font-bold text-zinc-600 uppercase tracking-widest">
                <span>1M</span>
                <span>500M</span>
                <span>1B+</span>
              </div>
            </div>

            <div className="pt-8 border-t border-zinc-800/50 grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="space-y-2">
                <div className="text-zinc-500 font-black uppercase text-[10px] tracking-widest">Conservative Est.</div>
                <div className="text-3xl md:text-4xl font-black text-white tracking-tighter">
                  {formatCurrency(minEarnings)}
                </div>
              </div>
              <div className="space-y-2">
                <div className="text-[#b0ff3e] font-black uppercase text-[10px] tracking-widest">High-End Potential</div>
                <div className="text-4xl md:text-5xl font-black text-[#b0ff3e] tracking-tighter glow-primary-text">
                  {formatCurrency(maxEarnings)}
                </div>
              </div>
            </div>
          </div>

          <div className="text-zinc-500 text-[10px] font-bold uppercase tracking-widest leading-relaxed max-w-md mx-auto">
            *Based on average Creator Fund, Brand Deals, and Affiliate payouts of $5,000 - $50,000 per 100M views.
          </div>
        </div>
      </div>
    </section>
  );
};
